version: '3.8'
services:
  backend:
    build: ./backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
  dashboard:
    build: ./frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend
    volumes:
      - ./frontend:/app
  shop-ui:
    build: ./shop-ui
    ports:
      - "3001:80"
    depends_on:
      - backend
